### ISSUE TITLE
Cross-compiling doesn't seem to work

### ISSUE THREAD

**Issue by samrat** [ryleelyman/SDL-libs#1]
Hello! I'm trying to use your fork to add SDL to my macOS XCFramework as described here: https://mitchellh.com/writing/zig-and-swiftui#making-a-universal-multi-arch-library

I'm adding a dependency like so:

```
const zig_sdl = b.dependency("SDL", .{
        .target = std.zig.CrossTarget{
            .cpu_arch = cpu_arch, // std.Target.Cpu.Arch,
            .os_tag = .macos,
            .os_version_min = target.os_version_min,
        },
        .optimize = optimize,
    });
```

But it seems it gets compiled to the default target(aarch64 for me), probably because of the `b.standardTargetOptions` here: https://github.com/ryleelyman/SDL-libs/blob/05201d52883ab26b0ac6375f8b668dac4e6d8725/build.zig#L3

**Comment by robbielyman** [comment]
interesting, I appear to be unable to reproduce this. or, put another way, I added the following to a `zig init-exe` project:

```zig
// build.zig
const cross_target: std.zig.CrossTarget = .{
    .cpu_arch = .x86_64,
    .os_tag = .macos,
};
const sdl = b.dependency("SDL", .{
    .target = cross_target,
});
exe.linkLibrary(sdl.artifact("SDL2"));
```

and then running `zig build` correctly fails to compile because I don't have headers for x86_64 macos on my aarch64 machine. without more knowledge of your `build.zig` I'm not sure of the best way to help you out.

**Comment by samrat** [comment]
Yeah this does seem to be an issue with my build.zig: https://gist.github.com/samrat/535feb280bf15414da58f2a15158b765?permalink_comment_id=4702425. If you check the `zig build` output in the last comment, the same SDL_ttf.a(aarch64) is passed to `libtool`.

Since the issue is likely not related to your project, maybe it would be better to continue the conversation in this Discord thread that I created: https://discord.com/channels/605571803288698900/1155418831678873680
